#!/usr/bin/env bash
# this file is called by .xinitrc to start some nice apps for dwm
# feh --bg-scale ~/fb-colorize1001010.png
urxvtd -q -f -o

xrdb -load $HOME/.Xresources &

# ibus
# export XMODIFIERS="@im=ibus"
# export GTK_TM_MODULE="ibus"
# export GT_IM_MODULE="ibus"
# ibus-daemon -x -r -d &

# fcitx
export XMODIFIERS="@im=fcitx"
export GTK_IM_MODULE="fcitx" # or xim
export GT_IM_MODULE="fcitx" # or xim
export QT_IM_MODULE="fcitx" # or xim
export GTK_PATH=
fcitx # no need &, it run as daemon

# config HOME
export XDG_CONFIG_HOME=$HOME/.config

# set battery alert level
echo '180' > $HOME/.BATTERY_LEVEL_LIM
# 180:alert start when less than 18%

# daemon applications
# env - LANG="$LANG" /var/lib/dropbox/.dropbox-dist/dropboxd &
env - LANG="$LANG" /usr/bin/dropbox start
conky -c $HOME/.conky | while read -r; do xsetroot -name "$REPLY"; done &
# no BATTERY even note book,,,sad...
# conky -c $HOME/.conky | while read -r; do xsetroot -name "$REPLY"; /home/tknv/Scripts/CHECK-LOW-BATTERY; done &

# android notification service
# /usr/share/android-notifier-desktop/run.sh &
# python /home/tknv/.linconnect/LinConnectServer/main/linconnect_server.py &
# java -jar /usr/share/android-notifier-desktop/android-notifier-desktop.jar -t &

# /home/tknv/Downloads/copy/x86_64/CopyAgent &
# initialize radio devices, connect wifi AP, config trackpoint
# sudo $HOME/Scripts/du-init &

# Start Thinkpad OSD daemon
#if [ -x /usr/bin/tpb ] &&  [ -w /dev/nvram ] && [ -r /dev/nvram ]; then
#	/usr/bin/tpb -d
#fi

# for (nm-applet) and etc
exec ck-launch-session dbus-launch &

# start taskd
# export TASKDDATA=/var/taskserver
# /usr/local/bin/taskdctl start
# start btsync
# /home/tknv/Scripts/btsync
# for cutting blue light
# xflux -l 13.75 -g 100.57

# mpd user
# mpd /home/tknv/.config/mpd/mpd.conf

# finaly start dwm
while true; do
	dwm || exit
done
