#!/bin/bash
# fbterm-bi: a wrapper script to enable background image withfbterm
# usage: fbterm-bi /path/to/image fbterm-options
echo -ne "\e[?25l" # hide cursor
fbv -icuker "$1" << EOF
# fbi -a -fitwidth "$1" << EOF
q
EOF
shift
export FBTERM_BACKGROUND_IMAGE=1
exec fcitx-fbterm-helper "$@"
# echo -en "\e]P7ffffff"
# exec fbterm ## "$@"
