#!/bin/sh
now=`acpi -a | grep on-line | cut -d ' ' -f3`
sta="on-line"
if [ "$now" = "$sta" ]; then
	exit
else
	bt_level=`cat /home/tknv/.BATTERY_LEVEL_LIM`
	echo "`expr $bt_level - 20`" > /home/tknv/.BATTERY_LEVEL_LIM
	echo `cat /home/tknv/.BATTERY_LEVEL_LIM`
fi
exit
