#!/bin/sh
btnow=`acpi -b | cut -d , -f2`
acnow=`acpi -a | grep on-line | cut -d ' ' -f3`
acsta="on-line"
bat=${btnow/%%/0}
echo "bat = $bat"
echo $acnow
echo $acsta
lim=80
if [ "$bat" -lt "$lim" -a "$acnow" != "$acsta" ]
then
	/home/tknv/Scripts/DANGER-LOW-BATTERY /home/tknv/Scripts/WHEN-LOW-BATTERY-MENU &
else
	true
fi
