#!/bin/sh
sudo ip link set wlan0 up
sudo wpa_supplicant -B -Dwext -i wlan0 -c /home/tknv/iNetIDs/using
sudo dhclient wlan0

# Trackpoint setting
sudo sh -c 'echo -n 120 > /sys/devices/platform/i8042/serio1/speed'
sudo sh -c 'echo -n 250 > /sys/devices/platform/i8042/serio1/sensitivity'

# off radio device for save energy
sudo wwan off
sudo bluetooth off

exit
